// Naming:   PAGE_ACTION_STATUS
export const APP_LOGIN_SET = 'app/login/set'
export const APP_LOGOUT_SET = 'app/logout/set'

export const VOICE_ASSISTANT_START = 'voice/assistant/start'
export const VOICE_ASSISTANT_STOP = 'voice/assistant/stop'
export const VOICE_ASSISTANT_FAIL = 'voice/assistant/fail'
export const VOICE_ASSISTANT_TOGGLE = 'voice/assistant/toggle'
export const VOICE_LISTENING_START = 'voice/listening/start'
export const VOICE_LISTENING_STOP = 'voice/listening/stop'
export const VOICE_LISTENING_ERROR = 'voice/listening/error'
export const VOICE_FETCHDATA_LOAD = 'voice/fetchData/load'
export const VOICE_FETCHDATA_SUCCEED = 'voice/fetchData/succeed'
export const VOICE_FETCHDATA_FAIL = 'voice/fetchData/fail'
export const VOICE_FETCHVOICE_LOAD = 'voice/fetchVoice/load'
export const VOICE_FETCHVOICE_SUCCEED = 'voice/fetchVoice/succeed'
export const VOICE_FETCHVOICE_FAIL = 'voice/fetchVoice/fail'
export const VOICE_NAVIGATION_REDIRECT = 'voice/navigation/redirect'

export const LOGIN_EDITFORM_CHANGE = 'login/editForm/change'
export const LOGIN_LOGIN_LOAD = 'login/login/load'
export const LOGIN_LOGIN_SUCCEED = 'login/login/succeed'
export const LOGIN_LOGIN_FAIL = 'login/login/fail'

export const ADMIN_OPENSUBMENU_CHANGE = 'admin/openSubMenu/change'

export const USERLIST_FETCHITEMS_LOAD = 'userList/fetchItems/load'
export const USERLIST_FETCHITEMS_SUCCEED = 'userList/fetchItems/succeed'
export const USERLIST_FETCHITEMS_FAIL = 'userList/fetchItems/fail'
export const USERLIST_CHANGETABLE_CHANGE = 'userList/changeTable/change'
export const USERLIST_SEARCHTABLE_EDIT = 'userList/searchTable/edit'
export const USERLIST_SEARCHTABLE_SEARCH = 'userList/searchTable/search'

export const USERFORM_ENTER_RESET = 'userForm/enter/reset'
export const USERFORM_EDITFORM_CHANGE = 'userForm/editForm/change'
export const USERFORM_FETCHITEM_LOAD = 'userForm/fetchItem/load'
export const USERFORM_FETCHITEM_SUCCEED = 'userForm/fetchItem/succeed'
export const USERFORM_FETCHITEM_FAIL = 'userForm/fetchItem/fail'
export const USERFORM_CREATEITEM_LOAD = 'userForm/createItem/load'
export const USERFORM_CREATEITEM_SUCCEED = 'userForm/createItem/succeed'
export const USERFORM_CREATEITEM_FAIL = 'userForm/createItem/fail'
export const USERFORM_EDITITEM_LOAD = 'userForm/editItem/load'
export const USERFORM_EDITITEM_SUCCEED = 'userForm/editItem/succeed'
export const USERFORM_EDITITEM_FAIL = 'userForm/editItem/fail'
export const USERFORM_DELETEITEM_LOAD = 'userForm/deleteItem/load'
export const USERFORM_DELETEITEM_SUCCEED = 'userForm/deleteItem/succeed'
export const USERFORM_DELETEITEM_FAIL = 'userForm/deleteItem/fail'
